#!/usr/bin/env bash
set -e

export base_dir="$(cd "$(dirname "$0")" && pwd -P)"
export test_dir="$base_dir/.test"
export test_fixture_dir="$test_dir/fixture"

############################################################

# Test must never modify fixtures; they should make copies
# and modify those.
#
build_test_fixtures() {
    mkdir -p "$test_fixture_dir"
}

run_unit_tests() { 
    go test ./...
}

run_integration_tests() {
    output="$(go run git-ci.go)"
    expected="Ha ha ha!"
    [ "$expected" = "$output" ] || {
        echo " FAILURE:"
        echo "Expected: $expected"
        echo "  Actual: $output"
    }
}

############################################################

cd "$base_dir"
rm -rf "$test_dir"
build_test_fixtures
#run_unit_tests
run_integration_tests

# XXX Don't do this by default or you may overwrite a different
# version of git-ci.
#
# go install ./...
