#!/usr/bin/env bash
set -euo pipefail

PROJDIR=$(cd $(dirname "$0")/.. && pwd -P)
trepo_src="$PROJDIR"/tscript/test-repo
trepo_work="$PROJDIR"/.build/test-repo

echo "----- test-repo setup"
mkdir -p $(dirname "$trepo_work")
rm -rf "$trepo_work/"
cp -r "$trepo_src/" "$trepo_work/"
(   cd "$trepo_work"
    git init -q
    git add .
    git commit -q -m 'Test repository initial commit'
)

expected() {
    cat <<_____
━━━━━━━━━━━━ 10-pass
━━━━━━━━━━━━ 20-pass
_____
}

echo "----- git tscript"
(   #   Ensure git-tscript finds repo root from subdir.
    cd "$trepo_work"/empty
    #   Run sample tests "interactively" so that output is not recorded.
    git tscript -i | diff -u <(expected) -
)
