#!/usr/bin/env bash
set -euo pipefail

PROJDIR=$(cd $(dirname "$0")/.. && pwd -P)
trepo_src="$PROJDIR"/tscript/test-repo
trepo_work="$PROJDIR"/.build/test-repo
mkdir -p $(dirname "$trepo_work")
rm -rf "$trepo_work/"
cp -r "$trepo_src/" "$trepo_work/"
(
    cd "$trepo_work"
    git init
    git add .
    git commit -m 'Test repository initial commit'
    echo =====
    git status -bs
)
